### ISSUE TITLE
issue in Steam/Git description of mod

### ISSUE THREAD

**Issue by Lbphero** [rezecib/Rezecib-s-Rebalance#9]
Wx-78 is referred to as he/him in the description of the steam workshop and the github description of this mod. They go by they/them, as evidenced in numerous quotes, their compendium lore entry, youtube video descriptions, & dev comments. 

change "WX-78 drops all gears except one on death, but his overcharge stacks less" to "WX-78 drops all gears except one on death, but **their** overcharge stacks less" . 

Good day.

**Comment by rezecib** [comment]
Thanks, fixed.
